### ISSUE TITLE
There is a little bug in your code

### ISSUE THREAD

**Issue by jshahabodin** [jahongir7174/COCO2VOC#1]
Hi. thank you for your hard working. i found a bug in your code. actually it occurs on line 59. so what's the bug?
after doing the train data things it's turn for validation data. in your code there is a results variable. so after all of things for training data it starts from the beginning of the results variable. results variable has file names of train data and validation data. it doing great with train data and it copies all training data and create .txt file. but when it starts from beginning it actually starts again from train data names and wants copy this files from validation data folder to the IMAGES folder. but this names is for train data and it returns an error in line 59 that there is no directory and file .... .
best way for quick fix : i just separate the train annotations files and validations and i run main.py twice. first for the train data and after that i swap the annotations files with validation data and run main.py again.
btw, tnx for your hardworking

**Comment by jahongir7174** [comment]
thank you for reporting the issue, but I could not get the point.
can you make it clear?

**Comment by jahongir7174** [comment]
even train and validation labels are in one folder, train and validation file names are written to the '.txt' file separately
